import { useRef } from 'react'
import { LpLayout } from '@/layouts/LpLayout'
import { HeroSection } from '@/components/home/HeroSection'
import { QuoteSection } from '@/components/home/QuoteSection'
import { MarketplaceSection } from '@/components/home/MarketplaceSection'
import { JourneySection } from '@/components/home/JourneySection'
import { TestimonialsSection } from '@/components/home/TestimonialsSection'
import { ResultsSection } from '@/components/home/ResultsSection'
import { PricingSection } from '@/components/home/PricingSection'
import { FaqSection } from '@/components/home/FaqSection'
import { BookSection } from '@/components/home/BookSection'
import { useRevealOnScroll } from '@/hooks/useReveal'
import { useCountUp } from '@/hooks/useCountUp'
import { useLocale } from '@/lib/locale'

const META = {
  en: {
    title: 'Naano: B2B LinkedIn Creator Marketplace',
    description:
      'Find the creators your buyers already trust, launch campaigns in days, and track the clicks, leads and pipeline generated by every post.',
  },
  fr: {
    title: 'Naano : la marketplace de créateurs LinkedIn B2B',
    description:
      'Trouvez les créateurs auxquels vos acheteurs font déjà confiance, lancez vos campagnes en quelques jours et suivez les clics, les leads et le pipeline générés par chaque post.',
  },
}

export default function Home() {
  const { locale } = useLocale()
  const ref = useRef<HTMLDivElement>(null)
  useRevealOnScroll(ref)
  useCountUp(ref)
  return (
    <LpLayout variant="home" title={META[locale].title} description={META[locale].description}>
      <div ref={ref} key={locale}>
        <HeroSection />
        <QuoteSection />
        <MarketplaceSection />
        <JourneySection />
        <TestimonialsSection />
        <ResultsSection />
        <PricingSection />
        <FaqSection />
        <BookSection />
      </div>
    </LpLayout>
  )
}
