import { NavAnchor } from '@/components/lp/LpNav'
import { ArrowRight, ArrowRightSmall, LinkedInLogo, ShieldCheck, XLogo } from '@/components/lp/icons'
import { TRUST_LOGOS } from '@/data/home'
import { useT } from '@/lib/locale'

const copy = {
  en: {
    pill: 'Where B2B brands work with creators',
    h1a: 'The B2B LinkedIn',
    h1b: 'Creator Marketplace',
    p: 'Find the creators your buyers already trust, launch campaigns in days, and track the clicks, leads and pipeline generated by every post.',
    primary: 'Launch a campaign',
    secondary: 'See how NaanoX works',
    trusted: 'Trusted by modern B2B teams',
    caseStudy: 'CASE STUDY',
  },
  fr: {
    pill: 'Là où les marques B2B collaborent avec des créateurs',
    h1a: 'La marketplace des créateurs',
    h1b: 'Marketplace de créateurs',
    p: 'Trouvez les créateurs auxquels vos acheteurs font déjà confiance, lancez vos campagnes en quelques jours et suivez les clics, les leads et le pipeline générés par chaque post.',
    primary: 'Lancer une campagne',
    secondary: 'Voir comment NaanoX fonctionne',
    trusted: 'Adopté par les équipes B2B modernes',
    caseStudy: 'ÉTUDE DE CAS',
  },
}

export function HeroSection() {
  const t = useT()
  const c = t(copy)
  return (
    <>
      <div style={{ height: 74 }} />
      <div
        data-screen-label="Hero"
        style={{
          minHeight: 'calc(var(--hero-h, max(760px, calc(100dvh / (100vw / 1672px)))) - 74px)',
          padding: '40px 84px 60px 84px',
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
          justifyContent: 'center',
          textAlign: 'center',
        }}
      >
        <div className="lp-cloud-scene">
          <img src="/lp/hero-clouds-cotton-blue-v7.png" alt="" className="lp-cloud-image" decoding="async" fetchPriority="high" />
        </div>
        <div
          style={{
            display: 'inline-flex',
            alignItems: 'center',
            gap: 10,
            background: '#FFFFFF',
            border: '1px solid #EBE9E5',
            borderRadius: 999,
            padding: '9px 18px 9px 14px',
            boxShadow: '0 1px 2px rgba(23,24,28,0.04)',
          }}
        >
          <XLogo />
          <LinkedInLogo />
          <span style={{ fontSize: 15, fontWeight: 500, color: '#33353B' }}>{c.pill}</span>
        </div>
        <h1
          style={{
            margin: '40px 0 0 0',
            fontSize: 77,
            lineHeight: 1.05,
            fontWeight: 600,
            letterSpacing: '-0.04em',
            color: '#17181C',
            maxWidth: 980,
          }}
        >
          {c.h1a}
          <br />
          {c.h1b}
          <span style={{ color: '#111318' }}>.</span>
        </h1>
        <p style={{ margin: '30px 0 0 0', fontSize: 21, lineHeight: 1.5, color: '#43454C', maxWidth: 660 }}>{c.p}</p>
        <div style={{ display: 'flex', alignItems: 'center', gap: 24, marginTop: 44 }}>
          <NavAnchor
            href="/register"
            className="lp-hero-primary"
            style={{
              display: 'inline-flex',
              alignItems: 'center',
              gap: 11,
              textDecoration: 'none',
              whiteSpace: 'nowrap',
              background: '#17181C',
              color: '#FFFFFF',
              fontSize: 16,
              fontWeight: 600,
              padding: '16px 28px',
              borderRadius: 12,
            }}
          >
            {c.primary}
            <ArrowRight size={17} />
          </NavAnchor>
          <NavAnchor
            href="/#how-it-works"
            className="lp-hero-secondary"
            style={{
              display: 'inline-flex',
              alignItems: 'center',
              gap: 9,
              textDecoration: 'none',
              whiteSpace: 'nowrap',
              color: '#17181C',
              fontSize: 16.5,
              fontWeight: 600,
            }}
          >
            {c.secondary}
            <ArrowRight size={16} stroke="#111318" />
          </NavAnchor>
        </div>
        <div style={{ display: 'flex', alignItems: 'center', gap: 11, marginTop: 34, color: '#55575E' }}>
          <ShieldCheck />
          <span style={{ fontSize: 15.5, fontWeight: 500 }}>{c.trusted}</span>
        </div>

        {/* Trust bar: infinite marquee of client logos, case-study chip first */}
        <div data-screen-label="Trust bar" style={{ width: '100%', marginTop: 48, padding: 0 }}>
          <div
            style={{
              overflow: 'hidden',
              WebkitMaskImage: 'linear-gradient(90deg, transparent, #000 8%, #000 92%, transparent)',
              maskImage: 'linear-gradient(90deg, transparent, #000 8%, #000 92%, transparent)',
            }}
          >
            <div className="naano-trust-track" style={{ display: 'inline-flex', alignItems: 'center', animation: 'naanoMarquee 26s linear infinite' }}>
              {[0, 1].map((rep) => (
                <TrustRun key={rep} caseStudy={c.caseStudy} ariaHidden={rep === 1} />
              ))}
            </div>
          </div>
        </div>
      </div>
    </>
  )
}

function TrustRun({ caseStudy, ariaHidden }: { caseStudy: string; ariaHidden: boolean }) {
  return (
    <>
      <NavAnchor
        href="/#what-people-think"
        style={{ textDecoration: 'none', display: 'flex', alignItems: 'center', justifyContent: 'center', padding: '0 36px', flexShrink: 0 }}
      >
        <span
          className="cs-chip"
          style={{
            display: 'inline-flex',
            alignItems: 'center',
            gap: 12,
            border: '1px solid #E4E1DC',
            borderRadius: 999,
            padding: '8px 9px 8px 18px',
            background: '#FFFFFF',
            boxShadow: '0 2px 10px rgba(23,24,28,0.05)',
          }}
        >
          <img src="/lp/logo-blogseo.png" alt="BlogSEO" style={{ height: 19, maxWidth: 120, objectFit: 'contain', display: 'block' }} />
          <span
            style={{
              display: 'inline-flex',
              alignItems: 'center',
              gap: 5,
              background: 'rgba(17,19,24,0.06)',
              color: '#111318',
              fontSize: 11,
              fontWeight: 700,
              letterSpacing: '0.08em',
              padding: '5px 11px',
              borderRadius: 999,
            }}
          >
            {caseStudy}
            <ArrowRightSmall />
          </span>
        </span>
      </NavAnchor>
      {TRUST_LOGOS.map((l) => (
        <div key={l.src} style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', padding: '0 36px', flexShrink: 0 }} aria-hidden={ariaHidden}>
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', width: 152, height: 48 }}>
            <img
              src={l.src}
              alt={ariaHidden ? '' : l.alt}
              style={{
                maxHeight: l.marqueeHeight,
                maxWidth: 152,
                objectFit: 'contain',
                display: 'block',
                filter: 'grayscale(1)',
                opacity: 0.5,
                mixBlendMode: l.multiply ? 'multiply' : undefined,
              }}
            />
          </div>
        </div>
      ))}
    </>
  )
}
