import raw from './blog-listing.json'
import type { Locale } from '@/lib/locale'

/** Typed view over `blog-listing.json` (generated by `scripts/extract-blog.mjs`). */

export type BlogDate = { iso: string; text: string }

export type BlogCardData = {
  slug: string
  gradient: string
  dot: string
  category: string
  title: string
  excerpt: string
  author: string
  initials: string
  readMinutes: number
  readLabel: string
  date: BlogDate | null
}

export type BlogListing = {
  docTitle: string
  description: string
  eyebrow: string
  count: string
  h1: string
  intro: string
  topicsLabel: string
  topics: string[]
  latestLabel: string
  readArticle: string
  moreLabel: string
  moreCount: string
  featured: BlogCardData | null
  cards: BlogCardData[]
}

type BlogListingData = { listing: { en: BlogListing; fr: BlogListing | null } }

const data: BlogListingData = raw

export function getBlogListing(locale: Locale): BlogListing {
  return (locale === 'fr' && data.listing.fr) || data.listing.en
}
