import raw from './blog-posts.json'
import type { Locale } from '@/lib/locale'

/** Typed view over `blog-posts.json` (generated by `scripts/extract-blog.mjs`). */

export type BlogDateRow = { label: string; iso: string; text: string }

export type BlogPostView = {
  slug: string
  lang: string
  docTitle: string
  description: string
  title: string
  excerpt: string
  category: string
  readMinutes: number
  readLabel: string
  langLabel: string
  back: string
  gradient: string
  dot: string
  published: BlogDateRow | null
  updated: BlogDateRow | null
  author: { name: string; role: string; linkedin: string; avatar: string }
  alternate: { label: string; lang: string; href: string; text: string } | null
  tocLabel: string
  toc: { id: string; text: string }[]
  tags: string[]
  cta: { eyebrow: string; title: string; text: string; href: string; button: string; arrow: string }
  body: string
}

/** English page plus, for the two translated posts, the French capture (`fr`). */
export type BlogPost = BlogPostView & { fr?: BlogPostView }

type BlogPostsData = { proseClass: string; posts: BlogPost[] }

const data: BlogPostsData = raw

export function getBlogPost(slug: string | undefined): BlogPost | undefined {
  return slug ? data.posts.find((p) => p.slug === slug) : undefined
}

/** The post as rendered for a locale: the French capture when one exists, else the English page. */
export function getBlogPostView(post: BlogPost, locale: Locale): BlogPostView {
  return (locale === 'fr' && post.fr) || post
}
