/**
 * Types for the captured creator profiles (see scripts/extract-creators.mjs and
 * scripts/split-creators.mjs). Profiles are fetched one at a time from
 * public/data/creators/<slug>.json.
 */

export type StatKey =
  | 'followers'
  | 'avgViews'
  | 'avgReactions'
  | 'avgComments'
  | 'engagement'
  | 'basedIn'
  | 'impressions28d'
  | 'avgImpressions'
  | 'impressionsCoverage'

export type SeniorityKey = 'seniorityFounder' | 'seniorityVp' | 'seniorityManager' | 'senioritySenior' | 'seniorityOther'
export type FunctionKey =
  | 'functionFounders'
  | 'functionMarketing'
  | 'functionSales'
  | 'functionProduct'
  | 'functionEngineering'
  | 'functionDesign'
  | 'functionHr'
  | 'functionFinance'
  | 'functionConsulting'

export type EmptyNoteKey = 'audiencePending' | 'audienceLocked' | 'postsPending' | 'notEnoughEngagementData'
export type BadgeKey = 'availableToBook' | 'acceptingBookings' | 'paused'

export type CreatorStat = { key: StatKey; value: string }

export type CreatorPost = {
  /** LinkedIn media type label ("image", "text", "video"…), may be empty */
  type: string
  /** true when the post was booked through NaanoX (shows the "NaanoX" tag) */
  naano: boolean
  text: string
  reactions: string
  comments: string
  url: string
}

export type AboutSection = { kind: 'about'; position: string | null; bio: string | null; sectors: string[] }
export type AudienceSection = {
  kind: 'audience'
  cards: CreatorStat[]
  note: EmptyNoteKey | null
  updated: { n: number; unit: string } | null
}
export type PostsSection = { kind: 'posts'; posts: CreatorPost[]; empty: EmptyNoteKey | null }
export type EngagersSection = {
  kind: 'engagers'
  empty: boolean
  seniority: { key: SeniorityKey; value: string; width: string }[]
  /** null → the "By function" block is not rendered */
  functions: { key: FunctionKey; value: string }[] | null
}
export type PricingSection = { kind: 'pricing'; price: string; bundles: { count: number; price: string }[]; cta: string }
export type CustomSection = {
  kind: 'text' | 'logos'
  title: string
  body: string | null
  items: { href: string; name: string; favicon: string; title: string }[]
}

export type CreatorSection = AboutSection | AudienceSection | PostsSection | EngagersSection | PricingSection | CustomSection

export type CreatorProfile = {
  slug: string
  name: string
  firstName: string
  headline: string | null
  avatarUrl: string | null
  avatarInitial: string | null
  location: string | null
  sectors: string[]
  badge: BadgeKey | null
  headerStats: CreatorStat[]
  sections: CreatorSection[]
  ctaHref: string
  moreCreators: { label: string; href: string }[]
  title: string
  description: string
  meta: {
    followers: number | null
    engagement: string | null
    avgViews: number | null
    avgReactions: number | null
    avgComments: number | null
    statsUpdatedAt: string | null
    country: string | null
    linkedinUrl: string | null
    priceCents: number | null
    bundles: { posts: number; priceCents: number }[]
    acceptingBookings: boolean
    showPricing: boolean
    postsCount: number | null
    engagersTotal: number | null
  } | null
}

const cache = new Map<string, Promise<CreatorProfile | null>>()

/**
 * Fetches one captured creator profile from `/data/creators/<slug>.json`
 * (generated by `scripts/split-creators.mjs`). Unknown slugs resolve to null.
 */
export function findCreator(slug: string): Promise<CreatorProfile | null> {
  if (!/^[a-z0-9-]+$/.test(slug)) return Promise.resolve(null)
  let p = cache.get(slug)
  if (!p) {
    p = fetch(`/data/creators/${slug}.json`)
      .then((r) => (r.ok ? (r.json() as Promise<CreatorProfile>) : null))
      .catch(() => null)
    cache.set(slug, p)
  }
  return p
}
