/**
 * Typed view over `creators.json` (generated by `scripts/extract-creators.mjs`
 * from the captured /creators/<slug> pages). The file is ~3.5 MB, so it is
 * loaded on demand with a dynamic import and cached.
 */

export type StatKey =
  | 'followers'
  | 'avgViews'
  | 'avgReactions'
  | 'avgComments'
  | 'engagement'
  | 'basedIn'
  | 'impressions28d'
  | 'avgImpressions'
  | 'impressionsCoverage'

export type SeniorityKey = 'seniorityFounder' | 'seniorityVp' | 'seniorityManager' | 'senioritySenior' | 'seniorityOther'
export type FunctionKey =
  | 'functionFounders'
  | 'functionMarketing'
  | 'functionSales'
  | 'functionProduct'
  | 'functionEngineering'
  | 'functionDesign'
  | 'functionHr'
  | 'functionFinance'
  | 'functionConsulting'

export type EmptyNoteKey = 'audiencePending' | 'audienceLocked' | 'postsPending' | 'notEnoughEngagementData'
export type BadgeKey = 'availableToBook' | 'acceptingBookings' | 'paused'

export type CreatorStat = { key: StatKey; value: string }

export type CreatorPost = {
  /** LinkedIn media type label ("image", "text", "video"…), may be empty */
  type: string
  /** true when the post was booked through Naano (shows the "Naano" tag) */
  naano: boolean
  text: string
  reactions: string
  comments: string
  url: string
}

export type AboutSection = { kind: 'about'; position: string | null; bio: string | null; sectors: string[] }
export type AudienceSection = {
  kind: 'audience'
  cards: CreatorStat[]
  note: EmptyNoteKey | null
  updated: { n: number; unit: string } | null
}
export type PostsSection = { kind: 'posts'; posts: CreatorPost[]; empty: EmptyNoteKey | null }
export type EngagersSection = {
  kind: 'engagers'
  empty: boolean
  seniority: { key: SeniorityKey; value: string; width: string }[]
  /** null → the "By function" block is not rendered */
  functions: { key: FunctionKey; value: string }[] | null
}
export type PricingSection = { kind: 'pricing'; price: string; bundles: { count: number; price: string }[]; cta: string }
export type CustomSection = {
  kind: 'text' | 'logos'
  title: string
  body: string | null
  items: { href: string; name: string; favicon: string; title: string }[]
}

export type CreatorSection = AboutSection | AudienceSection | PostsSection | EngagersSection | PricingSection | CustomSection

export type CreatorProfile = {
  slug: string
  name: string
  firstName: string
  headline: string | null
  avatarUrl: string | null
  avatarInitial: string | null
  location: string | null
  sectors: string[]
  badge: BadgeKey | null
  headerStats: CreatorStat[]
  sections: CreatorSection[]
  ctaHref: string
  moreCreators: { label: string; href: string }[]
  title: string
  description: string
  meta: {
    followers: number | null
    engagement: string | null
    avgViews: number | null
    avgReactions: number | null
    avgComments: number | null
    statsUpdatedAt: string | null
    country: string | null
    linkedinUrl: string | null
    priceCents: number | null
    bundles: { posts: number; priceCents: number }[]
    acceptingBookings: boolean
    showPricing: boolean
    postsCount: number | null
    engagersTotal: number | null
  } | null
}

let cache: Promise<CreatorProfile[]> | null = null

/** Loads (and caches) every captured creator profile. */
export function loadCreators(): Promise<CreatorProfile[]> {
  if (!cache) cache = import('./creators.json').then((m) => m.default as CreatorProfile[])
  return cache
}

export async function findCreator(slug: string): Promise<CreatorProfile | null> {
  const all = await loadCreators()
  return all.find((c) => c.slug === slug) ?? null
}
